// frontend/src/lib/components/CategoryTree.svelte
<script>
	import { goto } from '$app/navigation';
	import CategoryNode from './CategoryNode.svelte';

	export let categories = [];
	export let currentSlug = null;
	export let useQueryParam = false; // 是否使用查詢參數而非路徑參數

	function handleCategoryClick(event) {
		const category = event.detail;
		if (category && category.level === 3) {
			if (useQueryParam) {
				goto(`/product?category=${category.slug}`);
			} else {
				goto(`/product/${category.slug}`);
			}
		}
	}
</script>

<div class="category-tree">
	{#each categories as category}
		<CategoryNode {category} {currentSlug} on:click={handleCategoryClick} />
	{/each}
</div>

<style>
	.category-tree {
		background-color: transparent;
	}
</style>

// frontend-vue/src/components/CategoryTree.vue
<template>
	<div class="category-tree">
		<CategoryNode
			v-for="category in categories"
			:key="category.id"
			:category="category"
			:current-slug="currentSlug"
			@click="handleCategoryClick"
		/>
	</div>
</template>

<script setup>
import CategoryNode from './CategoryNode.vue';
import { useRouter } from 'vue-router';

const props = defineProps({
	categories: {
		type: Array,
		default: () => []
	},
	currentSlug: {
		type: String,
		default: null
	},
	useQueryParam: {
		type: Boolean,
		default: false
	}
});

const router = useRouter();

function handleCategoryClick(category) {
	if (category && category.level === 3) {
		if (props.useQueryParam) {
			router.push(`/product?category=${category.slug}`);
		} else {
			router.push(`/product/${category.slug}`);
		}
	}
}
</script>

<style scoped>
.category-tree {
	background-color: transparent;
}
</style>
